name: mkdocs # (1)!
on:
  push:
    branches:
      - main
    paths:
      - 'mkdocs.yaml'
      - 'book/**'
      - '.github/workflows/build_book.yml'

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs jupyterlab==4.1.1 pymdown-extensions
      - name: Build docs directory from notebooks
        run: |
          rm -rf docs
          mkdir -p docs
          cp book/index.md docs/index.md
          find book -type f -name "*.ipynb" ! -path "*/.ipynb_checkpoints/*" -print0 \
            | xargs -0 -I{} jupyter nbconvert --to markdown --output-dir docs "{}"
      - run: mkdocs gh-deploy --force --remote-branch gh-pages # mkdocs gh-deploy --force